spring:
  profiles:
    active: dev
---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/msempleado?serverTimezone=UTC
    username: equiroz
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: validate
    show-sql: true

server:
  port: 8000